### ISSUE TITLE
HUGO_VERSION in netlify.toml

### ISSUE THREAD

**Issue by sadikkuzu** [bouncmpe/website#4]
https://github.com/bouncmpe/website/blob/589da0ce303b39c1ad665fb011a53ae4dfdd151a/netlify.toml#L8

Is it supposed to be `0.110.0` with respect to GitHub Actions [build](https://github.com/bouncmpe/website/blob/main/.github/workflows/pages.yml#L29) job?

**Comment by doganulus** [comment]
Not an error itself. It would become a problem if we had used a Hugo feature introduced after `0.101.0`. We could remove Netlify setup and use only GH Pages but there is a problem with icon rendering there: https://bouncmpe.github.io/website/

**Comment by sadikkuzu** [comment]
Oh, ok, I got it. Thanks.

By icon rendering, do you mean favicon?

**Comment by sadikkuzu** [comment]
If it is favicon,
configs seem ok
https://github.com/bouncmpe/website/blob/aa802c948c0e13a5d62739ec4881e28bf00a3406/config/_default/config.yml#L15-L16
and there is logo.png in [assets/images](https://github.com/bouncmpe/website/tree/main/assets/images) directory.

In my local environment, first I tried to put logo.png file into [static](https://github.com/bouncmpe/website/tree/main/static) folder, as in:
https://stackoverflow.com/a/42043649/7030591
After running `hugo server`, I couldn't see a favicon in http://localhost:1313/ again.


Maybe is it because there is no `<link rel="icon" type="image/png" href="...">` in [head.html](https://github.com/bouncmpe/hugo-theme-department/blob/main/layouts/partials/head.html) of [hugo-theme-department](https://github.com/bouncmpe/hugo-theme-department) theme?
Like `<link rel="shortcut icon" type="image/png" href="/img/icon-192x192.png">` as in
https://stackoverflow.com/a/69817960/7030591

**Comment by doganulus** [comment]
The problem I have mentioned is solved here at https://github.com/bouncmpe/hugo-theme-department/commit/1f7419f1cd68485c35c8d06e63c2f9c0ef27e80e.

We needed to add `{{ site.BaseURL }}` prefix asset links to work them across under different serve directories. Netlify serves the site directly under subdomain ([bouncmpe.netlify.app](https://bouncmpe.netlify.app)) but GitHub Pages does it under a subdirectory ([bouncmpe.github.io/website/](https://bouncmpe.github.io/website/)). This difference was the problem. 

The prefix `{{ site.BaseURL }}` ensures that the correct prefix is used. This variable is adjustable at build time via `-b` flag such as `hugo -b <base_url>`.

**Comment by sadikkuzu** [comment]
Oh, I see.

Yes, interesting case
and cool solution 👍🏼

**Comment by sadikkuzu** [comment]
Then now, we can go on using both GitHub Pages and Netlify, right?

**Comment by sadikkuzu** [comment]
I can create a PR for `netlify.toml` and
https://github.com/bouncmpe/website/blob/aa802c948c0e13a5d62739ec4881e28bf00a3406/.devcontainer/Dockerfile#L1

**Comment by doganulus** [comment]
Yes, it is usually better to use a recent version without allowing too much drift. You can change the version and test it locally. And make a PR.

**Comment by sadikkuzu** [comment]
Sure 👍🏼 
Thanks for the detailed information 🙏🏼
